name: Deploy
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - name: Deploy
        run: |
          bundle exec asciidoctor -a toc="left" -a toclevels=2 README.adoc -o docs/index.html
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          if (git diff --shortstat docs/index.html | grep '[0-9]'); then \
            git add docs/index.html
            git commit -m "Update docs"
            git push origin HEAD:${GITHUB_REF}
          fi
